[package]
name = "raytracer"
version = "0.1.0"
authors = ["Jana Lemke <jana.lemke@rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rayon = "*"

[profile.release]
debug = true
